FROM registry.access.redhat.com/ubi9/ubi

RUN dnf install -y wget nc && dnf clean all

RUN wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for \
  && chmod +x /usr/bin/wait-for

COPY --from=minio/mc /usr/bin/mc /usr/bin/mc

RUN echo '#!/bin/sh' > /usr/bin/init.sh && \
  echo '/usr/bin/mc alias set myminio http://going2test-minio:9000 going2minio going2minio' >> /usr/bin/init.sh && \
  echo '/usr/bin/mc mb myminio/g2bucket' >> /usr/bin/init.sh && \
  echo '/usr/bin/mc anonymous set public myminio/g2bucket' >> /usr/bin/init.sh && \
  echo 'exit 0' >> /usr/bin/init.sh && \
  chmod +x /usr/bin/init.sh